### ISSUE TITLE
voice chat unavailable

### ISSUE THREAD

**Issue by W0ND585** [henkelmax/simple-voice-chat#220] opened 2021-06-13 02:09 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version
- Forge version
- Mod version

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by W0ND585** [comment] 2021-06-13 02:14
I tried doing /voice chat test and it said can not connect  to the client

**Comment by henkelmax** [comment] 2021-06-13 08:04
Duplicate of #112, #104, #98, #97, #115, #124, #146, #152, #153, #160, #169, #178, #203 and many others.

**Closed as completed by henkelmax** 2021-06-13 08:04 UTC
Labels: bug
