### ISSUE TITLE
Port is open, but i can't connect

### ISSUE THREAD

**Issue by Mudxiej** [henkelmax/simple-voice-chat#160] opened 2021-04-21 21:51 UTC
I set my port in my minecraft server to be opened and nothing changed. Server is running and the port is binded corectly: "Server started at port 24454". When i join, there is crossed plug sign, and info about no connection. I used the netcat (only on the server, i cant open it up on client idk why, its crashing after puting the line in), and on server it worked, i got text back. What do i do then?

**Comment by Mudxiej** [comment] 2021-04-22 06:43
also on the opened port tool i checked if it opened, It is.

**Comment by henkelmax** [comment] 2021-04-22 07:31
Duplicate of #112, #104, #98, #97, #115, #124, #146, #152, #153 and many others.

**Closed by henkelmax** 2021-04-22 07:31 UTC
Labels: question
