### ISSUE TITLE
One person cant hear. but everyone else.

### ISSUE THREAD

**Issue by graciekaeri** [henkelmax/simple-voice-chat#49] opened 2021-02-09 00:21 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Everyone has ease with playing the mod, it works for everyone else and we  sometimes cant hear eachother but we manage to fix it,**

Me and my friends (5) all of our voicechats work and we can hear each other, we have problems sometimes but we manage to fix it. But then we added another friend to our server, and his voice chat won't work. When he joins, he can hear us and we can hear him, but after he loads in he cant hear us and we cant hear him anymore. Sometimes we can see the voice icon, but its irregular and is random.

**- We set up his microphone to his microphone and his speakers and its the correct ones.
- Amplified the voice and turned up volume, and also tried pressing M."
- We also tried reinstalling the mod multiple times, and also reinstalling different versions. (1,16.x works with any 1.16.x)
- He restarted his entire PC
- Reinstalled the modpack
- We're using curseforge and we tried clicking the repair profile option.
- We went on discord and see if the thing matched the input/output of the one in game.
- We turned up in-game volume in minecraft.
- We tried caps lock and voice activity
- He lives in the same state as our friends and theirs work so its not a lag/connection problem.**
-
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
I expected that the mod would work because it worked for everyone else and we used the same problem solving options as we did the others, and more.

My Logs (Successfully Works) : https://docs.google.com/document/d/19KyyRLqAHq6eDS2kIhKgPrnYkM1tUz9AyXmpwwOQ3JY/edit

Mod Logs from "Open latest.log" :
https://docs.google.com/document/d/1OeM1JI5EZSfMH3LlwUfbDcR5n30P6toJfvwefU8jq74/edit

Friend's Logs (Unsuccessfully works) :
https://docs.google.com/document/d/15LQuNd0iQKOu71GHyRF-jyoIORirp8a0AvovR7jA8-k/edit

There are quite a bit of errors for the other mods for the car and gun mod, but despite that the voice mod still worked for everyone else and didnt affect any gameplay.

**Versions**
- Mod Version 1.16.4
- Forge Version forge-35.1.4
- Server Version 1.16.4

**Other mods**
-  [1.16.4] SecurityCraftv1.8.20.2 (SecurityCraft)
- ava- 1.5.8
- chiselsandbits-0.2.9-RELEASE (ChiselandBits)
- economyinc- 1.6.9.4 (EconomyInc Mod)
- fairylights-4.0.4-1.16.4 (FairyLights)
- furniture-7.0.0-pre19-1.16.3 (MrCrayfish's Furniture)
- headshot-1.06 (Headshot .fabric mod)
- mcw-furniture-2.0.0-mc1.16.4 (Macaw's Furniture)
- obfuscate-0.5.1-1.16.3 (Obfuscate)
- pamhc2foodcore-1.16.3-1.0.0 (Pams HarvestCraft 2 Foodcore)
- pamhc2crops- 1.16.3-1.0.1 (Pams HarvestCraft 2 Crops)
- pamhc2foodextended-1.16.3-1.0.0 (Pams HarvestCraft 2 Foodextended)
- pamhc2trees-1.16.3-1.0.0 (Pams HarvestCraft 2 Trees)
- skinned-lanterns-1.16.4-1.3.1 (Skinned Lanterns)
- torohealth-1.16.4-forge-4 (ToroHealth Damage Indicators)
- vehicle-mod-0.45.2-1.16.3 (MrCrayfish Vehicle mod)
- voicechat-1.16.4-1.1.5 (Simple Voice chat)

No screenshots available.

**Comment by henkelmax** [comment] 2021-02-09 08:16
Duplicate of #38

**Closed by henkelmax** 2021-02-09 08:16 UTC
Labels: bug

**Comment by LemonStar132** [comment] 2024-08-23 16:26
Hi this is very clearly not a duplicate of #38
And this bug HAS NOT been fixed, 3 years later! I am experiencing the same bug described in the issue above, and after reading #38. I can confidently say this is a completely different issue. In 38, OP says the issue is that the person can be heard, but they cant hear anything. In this post, OP says that everyone else is fine and can hear and talk, but one person isn't able to be heard or hear others. Please fix this bug and don't just overlook this as a "duplicate".

**Comment by henkelmax** [comment] 2024-08-23 17:15
This is a 3 year old issue @LemonStar132. 
If you need help setting up the voice chat visit the discord.
