### ISSUE TITLE
Strange errors in console.

### ISSUE THREAD

**Issue by gamecrinkles** [henkelmax/simple-voice-chat#29] opened 2021-01-19 19:58 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Occasionally I will get this error in my console repeatedly and voice chat begins to lag. [19.01 13:52:25] [Server] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:176]: 	at java.net.PlainDatagramSocketImpl.send(Native Method) [19.01 13:52:25] [Server] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:176]: 	at java.net.DatagramSocket.send(DatagramSocket.java:693) [19.01 13:52:25] [Server] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:176]: 	at de.maxhenkel.voicechat.voice.common.NetworkMessage.sendTo(NetworkMessage.java:143) [19.01 13:52:25] [Server] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:176]: 	at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:170) [19.01 13:52:25] [Server] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:176]: java.io.IOException: Operation not permitted (sendto failed)

**Steps to reproduce the issue**
Unsure.
**Expected behavior**
Voice chat to work consistently.

**Log files**
https://pastebin.com/JMMRSu6E

**Versions**
- 1.16.4
- 35.1.32
- 1.16.4-1.1.3

**Other mods**
![image](https://user-images.githubusercontent.com/77459568/105086032-42425080-5a5e-11eb-945b-2a17b49408ad.png)

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment] 2021-01-19 20:29
Duplicate of #28

**Closed by henkelmax** 2021-01-19 20:29 UTC
Labels: bug
