### ISSUE TITLE
Voicemod unavailable 

### ISSUE THREAD

**Issue by Solti2** [henkelmax/simple-voice-chat#115] opened 2021-03-19 19:22 UTC
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**

It won't function on servers and I also tried it on atwrnos and it didn't work. Why?

**Comment by henkelmax** [comment] 2021-03-19 19:46
Duplicate of #112, #104, #98, #97 and many others.

**Closed by henkelmax** 2021-03-19 19:46 UTC
Labels: question
