### ISSUE TITLE
[Suggestion] Sound filters / dynamic surroundings reverb compatibility

### ISSUE THREAD

**Issue by MrKashew** [henkelmax/simple-voice-chat#114] opened 2021-03-18 05:05 UTC
Probably difficult to implement (I imagine the sound would have to be rendered as "physically" in the game?) and something that has already been considered at some point

**Comment by henkelmax** [comment] 2021-03-18 08:09
Duplicate of #96

**Closed by henkelmax** 2021-03-18 08:09 UTC
Labels: enhancement
