### ISSUE TITLE
Voice chat won't work

### ISSUE THREAD

**Issue by Chwisty** [henkelmax/simple-voice-chat#212] opened 2021-06-09 17:30 UTC
Me and a couple of my friends are having the same problem on all of the servers we are trying to play on where it shows up with a plug with a red line across it in the bottom left. Anyone know how to fix this? (We are using fabric)

Fabric Version:  
fabric-loader-0.11.3-1.17.jar
fabric-api-0.34.9+1.17.jar
voicechat-1.17-1.0.2.jar

**Comment by Chwisty** [comment] 2021-06-09 17:34
We also tried testing voicechat in game using "/voicechat test *name*" and it said "Client not connected"

**Comment by henkelmax** [comment] 2021-06-09 17:43
Duplicate of #112, #104, #98, #97, #115, #124, #146, #152, #153, #160, #169, #178, #203 and many others.

**Closed as completed by henkelmax** 2021-06-09 17:43 UTC
Labels: bug
