### ISSUE TITLE
Other players can hear, but some can't.

### ISSUE THREAD

**Issue by Santierossa** [henkelmax/simple-voice-chat#68] opened 2021-02-23 01:28 UTC
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**
It says it has been answered, but neither of these players are using mac. They can talk but cannot hear no matter what.

**Comment by henkelmax** [comment] 2021-02-23 09:07
Duplicate of #23

**Closed by henkelmax** 2021-02-23 09:07 UTC
Labels: question
