### ISSUE TITLE
Issue with voice chat being unavailable and timing out.

### ISSUE THREAD

**Issue by lilphantom25** [henkelmax/simple-voice-chat#98] opened 2021-03-11 20:05 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
I have checked with the server host and they have said it's all ready to go just need to do the voice port in the file. I have done that and it all seems to run perfectly well, however, when we try to use the keybinds in-game it says 'voice chat is unavailable' and in the console/log it says it's times out when connecting to the player.

**Steps to reproduce the issue**
try and do the in-game keybinds.

**Expected behavior**
Expected to have the keybinds operate properly.

Lastest Log file attached

**Versions**
- 1.16.5
- Fabric 1.16.5 (latest version our host provides)
- voicechat-1.16.5-1.0.9

**Other mods**
fabric-api 0.32.0
lithium-fabric 1.16.5-0.6.4
LuckPerms-Fabric 5.2.92
Have tested voice chat without the extra mods and with them the same result.

**Screenshots (Optional)**
Screenshots of the issue.
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/6125566/latest.log)

**Comment by henkelmax** [comment] 2021-03-11 20:06
Duplicate of #81

**Closed by henkelmax** 2021-03-11 20:06 UTC
Labels: bug

**Comment by lilphantom25** [comment] 2021-03-11 20:09
Why is this being closed

**Comment by henkelmax** [comment] 2021-03-11 20:15
Because its a duplicate

**Comment by lilphantom25** [comment] 2021-03-11 20:17
but it isnt because its different server and server details. maybe the same issue but the reason its happening could be different

**Comment by lilphantom25** [comment] 2021-03-11 20:22
maybe a video uploaded how to do this would be helpful

**Comment by henkelmax** [comment] 2021-03-11 20:22
Have you tried the suggested solution?

**Comment by lilphantom25** [comment] 2021-03-11 20:24
I have replied to that... yes, I have put the server IP on the bind-address and its still the same issue

**Comment by henkelmax** [comment] 2021-03-11 20:25
> maybe a video uploaded how to do this would be helpful

Cited from CurseForge:

> There is no "single" way to do it. It's different for every server provider and every ISP.
So, no there won't be a video. Either you know how to forward a port or not.

**Comment by lilphantom25** [comment] 2021-03-11 20:27
I have spoken with my server host and the forward port is all set up

**Comment by henkelmax** [comment] 2021-03-11 20:29
Have you tried everything in the wiki?

**Comment by lilphantom25** [comment] 2021-03-11 20:30
I have yes

**Comment by henkelmax** [comment] 2021-03-11 20:30
And netcat worked?

**Comment by lilphantom25** [comment] 2021-03-11 20:34
in the server console it showed 'Unknown or incomplete command, see below for error'
client console it just closed after the command

**Comment by henkelmax** [comment] 2021-03-11 20:39
So, you don't know if it works?

**Comment by lilphantom25** [comment] 2021-03-11 20:55
Well I mean it shows on the server so I presume it works. in that case, if I'm having the issue that doing what it says in the wiki with the console... what do I do to fix that?

**Comment by henkelmax** [comment] 2021-03-11 21:09
> Well I mean it shows on the server so I presume it works.
No. This happens if the client can send to the server, but the server can't send to the client.
This is mostly caused by not binding to the correct address.

> in that case, if I'm having the issue that doing what it says in the wiki with the console... what do I do to fix that?

What do you mean?

**Comment by lilphantom25** [comment] 2021-03-11 21:19
hey can you tell me what netcat is i get your not tech support but any help is much welcomed we really want this to work. do we install this nc111nt into the mods folder on the server because it doesnt look like a mod so i kept it seperate but i just wanted to ask thank you for your cooperation

**Comment by henkelmax** [comment] 2021-03-11 21:22
It is a tool for reading and writing to network connections. I just use it to check if the port is forwarded correctly. It has absolutely nothing to do with Minecraft.

**Comment by lilphantom25** [comment] 2021-03-11 21:26
ok well can we start from the begining here, so i have netcat and it says on the wiki i should install it to the server and the client, is that my minecraft server and minecraft client or something else? i just want to know im getting this right because there is something in here that im not getting

**Comment by lilphantom25** [comment] 2021-03-11 21:29
and is it normal for my firewall to be have a hissy fit? id rather not get any viruses from this xD

**Comment by henkelmax** [comment] 2021-03-11 21:35
I'm sorry, but I am not tech support. You have to search for it on the web or ask someone you know. I cant help everyone that has problems with their setup.

**Comment by lilphantom25** [comment] 2021-03-11 21:39
you do know issue help is tech support right?

**Comment by henkelmax** [comment] 2021-03-11 21:40
This issue tracker is just for bugs.
