### ISSUE TITLE
Microphone Permission Issue on MacOS

### ISSUE THREAD

**Issue by naliuj** [henkelmax/simple-voice-chat#320] opened 2021-12-08 23:44 UTC
**Bug description**

Microphone permission dialogue doesn't work for MacOS. I tried both MultiMC and the default launcher with no luck. It results in an exit code 1.

**Steps to reproduce the issue**
1. Launch minecraft
2. Drag the launcher to the microphone permission window.
3. Results in exit code 1

**Expected behavior**

It should grant microphone permission and launch the game.

**Log files**

https://pastebin.com/raw/P9NgReGd

**Versions**
- Minecraft version 1.18
- Fabric version 0.12.8
- Mod version 1.18.6.1

**Other mods**

The problem persists when no other mods are installed.

**Comment by henkelmax** [comment] 2021-12-08 23:46
Duplicate of #24.
Please add your issue to that and if its valid, I will reopen it.

**Closed as completed** 2021-12-08 23:47 UTC
Labels: duplicate

**Comment by Vizxls** [comment] 2023-07-09 01:30
show me yt tutorial plz
