### ISSUE TITLE
Disconnected from server, resetting proxy config values

### ISSUE THREAD

**Issue by smertVkedax** [henkelmax/simple-voice-chat#740] opened 2024-09-12 21:01 UTC
### Confirmation

- [X] I have read the wiki

### Bug description

minecraft 1.20.1 everything freezes in the game, mobs don't move and nothing is mined. And it doesn't exit the game unless you forcefully close it. In the logs, voice chat is to blame and it says: Disconnected from server, resetting proxy config values ​​and so on every time!

### Minecraft version

1.20.1

### Mod/Plugin version

1.20.1-2.5.21

### Mod/Plugin loader and version

fabric-0.16.5

### Steps to reproduce

Enter single player survival mode and play until it freezes.

### Expected behavior

solution to the problem!

### Log files

https://gist.github.com/smertVkedax/3005febd97fa79cfa8b7a0ae93079e6f

**Comment by henkelmax** [comment] 2024-09-12 21:06
This does not seem to be an issue with the voice chat mod. Please check if it still happens with just the voice chat mod installed. Please also check if it happens without the voice chat mod installed.

I also need very detailed instructions on how to reproduce the issue, since I'm not able to reproduce this at all.

**Comment by henkelmax** [comment] 2024-09-14 16:29
I'll close this for now. Feel free to reopen.

**Closed as not planned by henkelmax** 2024-09-14 16:29 UTC
Labels: triage
