### ISSUE TITLE
[1.16.5 backport regression] Multiplayer Server crash on startup, com/sun/jna/Platform class not found

### ISSUE THREAD

**Issue by Colin-J-Wood** [henkelmax/simple-voice-chat#378] opened 2022-02-25 23:11 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Dedicated servers fail to load on startup due to jna issues.  Please make sure your code is working on jna 4 for dedicated servers.

**Steps to reproduce the issue**
1. Install on dedicated server
2. Attempt to load

**Expected behavior**
The codebase should adhere to the JNA4 standard which has quite a few differences in classes.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.16.5
- Forge/Fabric version 36.2.28
- Mod version: 2.22.23

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/91890547/155815250-1d89d1c2-2b3c-46fb-9b98-a1cc94b0016a.png)

**Comment by henkelmax** [comment] 2022-02-26 07:42
Duplicate of #377

**Closed as completed** 2022-02-26 07:42 UTC
Labels: duplicate
