### ISSUE TITLE
I keep getting Voice Chat Unavailable

### ISSUE THREAD

**Issue by lilphantom25** [henkelmax/simple-voice-chat#97] opened 2021-03-11 19:27 UTC
Hi, I have spoken to the host of the server and they have said the voice port is open. I have put in multiple different ports but I keep getting Voice Chat Unavailable and the Console says I'm timing out.
![voicemond issues](https://user-images.githubusercontent.com/59034736/110843128-df23ac00-829f-11eb-8711-e57ceb284303.PNG)

**Comment by henkelmax** [comment] 2021-03-11 19:30
Duplicate of #81

https://github.com/henkelmax/simple-voice-chat/issues/81#issuecomment-791506206

**Comment by henkelmax** [comment] 2021-03-11 19:30
Next time please use the provided templates

**Closed by henkelmax** 2021-03-11 19:30 UTC
