### ISSUE TITLE
packets not being recieved

### ISSUE THREAD

**Issue by meulyn** [henkelmax/simple-voice-chat#35] opened 2021-01-24 15:57 UTC
24.01 10:35:58 [Server] VoiceChatPacketProcessingThread/INFO [Meuulyn: Request timed out]

So it seems like others have been able to use the voice mod just fine in my server but as for me and a few others there seems to be an issue where when we run the /voicetest it immediately returns with a [request timed out]. Unfortunately I'm not really sure what could be causing this and the people that do have it working on their end in our server didn't change anything except for keybinds for mute and PTT. We also haven't found any solution in the faq or in anyone elses question and bug tickets.

Attached is the log of our attempts and timeouts for packet retrieval as well as one of our other players receiving packets. Let us know if this suitable for a question or if this should be a bug report as well as any other information that you may need.

Any help would be greatly appreciated! thank you for your time~
[question ticket (voice mod).txt](https://github.com/henkelmax/simple-voice-chat/files/5862584/question.ticket.voice.mod.txt)

**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**

**Comment by henkelmax** [comment] 2021-01-24 16:00
```
24.01 09:54:31 [Server] VoiceChatPacketProcessingThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:182]: java.io.IOException: Operation not permitted (sendto failed)
24.01 09:54:31 [Server] VoiceChatPacketProcessingThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:182]: 	at java.net.PlainDatagramSocketImpl.send(Native Method)
24.01 09:54:31 [Server] VoiceChatPacketProcessingThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:182]: 	at java.net.DatagramSocket.send(DatagramSocket.java:693)
24.01 09:54:31 [Server] VoiceChatPacketProcessingThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:182]: 	at de.maxhenkel.voicechat.voice.common.NetworkMessage.sendTo(NetworkMessage.java:144)
24.01 09:54:31 [Server] VoiceChatPacketProcessingThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:182]: 	at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:175)
```

Duplicate of #28 and #29

**Closed by henkelmax** 2021-01-24 16:00 UTC
Labels: question

**Comment by meulyn** [comment] 2021-01-24 19:19
Thanks. I assume I have to contact my server provider about this.
Have a nice day!
