### ISSUE TITLE
Whispering and maybe shouting

### ISSUE THREAD

**Issue by Greenwolf20** [henkelmax/simple-voice-chat#262] opened 2021-07-26 21:32 UTC
**Is your feature request related to a problem? Please describe.**
There are many times when using this mod on a sort of RP server that we feel that you can't chat about secrets when others are nearby either just by coincidence or that they just have their house nearby and "live/work there". Another thing is sometimes someone might want to announce something to everyone and therefore wants to shout or if they are ontop of a tall building and can't talk to the people on the ground.

**Describe the solution you'd like**
Being able to optionally choose server side if you want to activate the use of a keybind to be able to whisper and maybe even one for shouting aswell. Distance for both whispering and shouting would be decided also using server side config. Possibly other icons when whispering/shouting to help avoid confusion.

**Describe alternatives you've considered**
The whispering and possibly shouting function would have to be optional in order to not cause any confusion to any normal use cases.

**Additional context**
Our use case is related to Youtube/Twitch content and we feel like this feature being added would really help improve the server for our use case overall.

I know that this whispering feature has been asked about before but i'm here showing support for it aswell. As I said, it doesn't have to be on by default.

Thank you for reading and thanks again for the mod!

**Comment by henkelmax** [comment] 2021-07-27 07:06
Duplicate of #149

**Closed as completed by henkelmax** 2021-07-27 07:06 UTC
Labels: enhancement
