### ISSUE TITLE
Connected Server Port, Yet VC Unvailable

### ISSUE THREAD

**Issue by afishofsorts** [henkelmax/simple-voice-chat#12] opened 2020-12-29 22:24 UTC
Through a BisectHosting Minecraft server (version 1.16.4) I've set up Forge (version 34.1.28) and Simple Voice Chat (version 1.0.4) such that the server console returns:

a)  Simple Voice Mod starts up on a port that the server uses and should be open (this port was changed in the config file)
         - [VoiceChatServerThread/INFO] [voicechat/]: Server started at port 8000
b) When a player connects they are authorized and connected to the mod successfully
         - [VoiceChatPacketProcessingThread/INFO] [voicechat/]: Successfully authenticated player 919bb7e6-1c48-4adf-b96d-70ff335aa090
c) The client side mod is installed for the player
d) There are no other mods present on the server

Despite checking these boxes, the prompt "Voice Chat Unavailable" still shows up

This is most likely something I've just screwed up in the setup, but in case it isn't I figured I'd open this.

**Comment by henkelmax** [comment] 2020-12-30 10:08
Duplicate of #10

**Closed by henkelmax** 2020-12-30 10:08 UTC
Labels: bug, duplicate
