### ISSUE TITLE
I hear others and myself (in testing mode) but nobody is hearing me...

### ISSUE THREAD

**Issue by PyZeee** [henkelmax/simple-voice-chat#230] opened 2021-06-22 18:11 UTC
Bug description

So I and a couple of others started a server a few weeks ago, containing this great mod and a couple of others (that are listed below). Back then it worked perfectly fine and we had a great time together, but when we started a new server yesterday, only I ran into some issues. After adding the mod *voicechat-1.16.5-1.5.8* like everyone else, I first thought that everything worked right because I tested my Blue Yeti with the "Enable microphone test" feature in the options. I have a little delay but everything is working fine while in testing-mode, I can adjust everything and so on, but when I try to speak to other humans, I run into the issue of people -whether I use ptt or just the normal voice- not hearing me, when I hear them crispy-clean due to this great mod. While I use my ptt-button, no icons are appearing and when I use open voice, I only see the icons if I mute myself. 

Summed up: Everything is working as it should, I hear myself in testing-mode, but other people don't hear me. 

Would be great if I could get some helping hands that would help me fix this since we're only going to use this great addition to the game for communicating! 

Have a great day :D 

![mod folder](https://user-images.githubusercontent.com/86316225/122976204-6b139c80-d394-11eb-9fe9-cea47f6ac0f5.PNG)
(mod folder)

**Comment by henkelmax** [comment] 2021-06-22 18:28
We are aware of this issue, but we are not able to reproduce it.
Can you please send me the logs of your client?
It would also be great if you can share your java version, OS and PC specs.
Is this just happening to you or to anybody else on your server?

**Comment by PyZeee** [comment] 2021-06-22 19:04
Heya, here are my logs:
[2021-06-22-7.log](https://github.com/henkelmax/simple-voice-chat/files/6696757/2021-06-22-7.log)

My java version: ![image](https://user-images.githubusercontent.com/86316225/122983641-82ef1e80-d39c-11eb-8593-189e755c5370.png)

And finally, my PC specs (2nd Van Gogh confirmed): ![image](https://user-images.githubusercontent.com/86316225/122984014-da8d8a00-d39c-11eb-808b-510d182c70ef.png)

And no, I did not hear from anybody that also got that issue. 

Thank you for actually caring about stuff.

**Comment by henkelmax** [comment] 2021-06-22 19:17
Thank you very much. I will look into it.

> Thank you for actually caring about stuff.

Of course :)

If you want, you can join our discord (https://discord.gg/4dH2zwTmyX).
This way communication might be a little quicker than on GitHub.

**Comment by henkelmax** [comment] 2021-06-22 20:56
It should be fixed with the latest alpha release on curse.
I was able to reproduce it myself.
Let me know if it works for you. If not I will reopen the issue.

**Closed as completed by henkelmax** 2021-06-22 20:56 UTC
Labels: bug
