### ISSUE TITLE
Bug: Can't join Hypixel with this mod on, it sends me to Limbo everytime.

### ISSUE THREAD

**Issue by Mr-Aerod** [henkelmax/simple-voice-chat#383] opened 2022-03-11 16:10 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version
- Forge/Fabric/Bukkit/Spigot/Paper version
- Mod/Plugin version

**Other mods**
A list of the other mods/plugins that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod/plugin is installed.
If not, please narrow down the mod(s)/plugin(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment] 2022-03-11 16:12
Duplicate of #296

**Closed as completed by henkelmax** 2022-03-11 16:12 UTC
Labels: duplicate, invalid
