### ISSUE TITLE
Mod is not working

### ISSUE THREAD

**Issue by Lama-MC** [henkelmax/simple-voice-chat#153] opened 2021-04-16 07:21 UTC
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**

After adding to aternos server and installing all files properly even on server. It is showing that voice chat is unavailable and on doing /test is is showing that the client is not connected

**Comment by henkelmax** [comment] 2021-04-16 07:22
Duplicate of #112, #104, #98, #97, #115, #124, #146, #152 and many others.

**Closed by henkelmax** 2021-04-16 07:22 UTC
Labels: question
