### ISSUE TITLE
Crash: java.lang.NoClassDefFoundError: de/maxhenkel/voicechat/api/events/DestroyOpenALContextEvent

### ISSUE THREAD

**Issue by viminio** [henkelmax/simple-voice-chat#634] opened 2023-11-02 04:29 UTC
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
The game closed and I don't know what to do.

**Steps to reproduce the issue**
Honestly I have no idea

**Expected behavior**
IDK

**Log files**
Logs
[Gist](https://gist.github.com/viminio/a64ada98e3450b6190a2558437e77110)

Crash-Report
[MCLo.gs](https://mclo.gs/fbcJUTY)
[Gist](https://gist.github.com/viminio/1c5bd7dd309c8a7f0cf2ae0e1d53e75b)

**Versions**
- 1.18.2
- Forge 40.2.10
- Mod 2.4.27 version

**Other mods**
AE2 Things
Alex's Mobs
AppleSkin
Applied Energistics 2
Architectury
Artifacts
Auudio 
Balm
Baubley Heart Canisters
Bonsai Trees 3
Bookshelf
Born in Chaos
Camera Mod
Citadel
CoFH Core
ColaConfig
CommonCapabilities 
Connectivity Mod 
Construction Wand
Controllable
CookingForBlockheads
Corpse 
CosmeticArmorReworked
Create 
Create Crafts & Additions
Create: Things and Misc
CreativeCore
Cristel Lib
Croptopia
Curios API
Customizable Player Models 
Cyclops Core
DarkUtilities
Delightful
Elevator Mod
Enemy Expansion
ExpandAbility
Explorer's Compass 
Extra USMP Sounds
Extractinator
Fakename 
FancyMenu
FancyMenu Audio Extension
Farmer's Delight 
Fastload-Reforged
Ferrite Core
Flywheel 
Forge
FPS Reducer
Freddy_fazcraft
Fusion 
GeckoLib 
Immersive Engineering
IntegratedDynamics 
Jade
JEI Integration
Journeymap
Just Enough Items
Just Enough Resources
Konkrete 
KubeJS 
Lazier AE2
LazyDFU
libnonymous
Lootr
Magnum Torch
Mantle 
Materialis
Minecraft
MixinExtras
MmmMmmMmmMmm
Mod Name Tooltip 
ModernFix
Mouse Tweaks
Nature's Compass 
OreExcavation
Paraglider
Patchouli
Pehkui 
PigPen 
Player Animator
PlayerRevive
Polymorph
Potions Master
Puzzles Lib
Rechiseled
Rechiseled: Create 
Relics 
Resourceful Lib
Rhino
Rubidium 
Rubidium Extra
Rubidium Extras
Runelic
SecurityCraft
Silent Gear
Silent Lib
Silent's Gems: Base
Simple Voice Chat
Smooth Boot (Reloaded)
Sophisticated Backpacks
Sophisticated Core 
Sophisticated Storage
Storage Drawers
SuperMartijn642's Config Libra
SuperMartijn642's Core Lib 
Terralith
Thermal Expansion
Thermal Series
Tinkers Reforged 
Tinkers' Construct 
Tinkers' Levelling Addon
Trash Cans
WaterFrames
WaterMedia
Waystones
When Dungeons Arise

**Screenshots (Optional)**
![image](https://github.com/henkelmax/simple-voice-chat/assets/62722905/812def34-afd4-4738-88af-097560281729)

**Comment by henkelmax** [comment] 2023-11-02 07:36
Duplicate of #607

**Closed as not planned by henkelmax** 2023-11-02 07:36 UTC
