### ISSUE TITLE
Certain unlucky players on my Twitch Affiliate SMP server are deaf and mute.

### ISSUE THREAD

**Issue by MajesticSammie** [henkelmax/simple-voice-chat#39] opened 2021-01-25 20:56 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**
I have.

**Bug description**
Most players can hear and speak with each other, but so far two different players have the same issue: they can't hear us, and we can't hear them. When they test their microphone, they can hear themselves, and occasionally, we can hear snippets of them. But for the most part, there's nothing.

**Troubleshooting we've already tried**
1. Muting and un-muting everyone
2. Checking to make sure everyone has the correct microphone and speaker setup
3. Turning up amplification
4. Switching between Push To Talk and Voice Activation

**Expected behavior**
Everyone should be able to hear and speak to everyone else.

**Log files**
All the logs are .gz files which don't look real pretty in Notepad.

**Versions**
- 1.16.4
- 35.1.15
- 1.1.3

**Other mods**
![image](https://user-images.githubusercontent.com/77994077/105764972-8e810b00-5f0c-11eb-9b0b-f657c36fc7d7.png)

**Screenshots (Optional)**
It's pretty self-explanatory.

**Comment by henkelmax** [comment] 2021-01-26 09:02
Duplicate of #38

**Closed by henkelmax** 2021-01-26 09:02 UTC
Labels: bug
