### ISSUE TITLE
Voice Chat Mod Showing VoiceChatPacketProcessingThread/WARN Failed to read packet from In Console

### ISSUE THREAD

**Issue by BitsCraft1** [henkelmax/simple-voice-chat#337] opened 2021-12-26 10:53 UTC
**Expected behavior**
I expected it to work instantly but it seems there was an error

**Log files**
[10:32:02] [VoiceChatServerThread/INFO]: Server started at port (port)
[10:32:03] [VoiceChatPacketProcessingThread/WARN]: Failed to read packet from / (ip)

**Versions**
- 1.18.1
- Fabric 1.18.1 (Latest)
- voicechat-fabric-1.18.1-2.1.28.jar

**Other mods**
Bobby
Sodium
Lithium
Fabric API

**Comment by henkelmax** [comment] 2021-12-26 11:42
This already has been fixed in 2.2.0-pre1. Please visit the discord in channel `#beta-testing` for the prerelease version.

**Closed as completed by henkelmax** 2021-12-26 11:42 UTC
Labels: duplicate

**Comment by lightjakee** [comment] 2021-12-27 11:35
It Still Does Not Work After Downloading The Newest Version

**Comment by henkelmax** [comment] 2021-12-27 11:38
This fix is only for some rare case when you are using bungeecord.
This error is not a bug it just indicates that another application is sending data to the UDP connection. This is mostly caused by bad DDoS protections or bad networking of the hoster. In some rare cases its just another application that just happens to send data to that port.

**Comment by lightjakee** [comment] 2021-12-27 11:54
Is There Any Way To Fix This?

**Comment by henkelmax** [comment] 2021-12-27 11:58
Switching the port.
