### ISSUE TITLE
Time out - Reconnect

### ISSUE THREAD

**Issue by Fastfingered** [henkelmax/simple-voice-chat#99] opened 2021-03-12 17:32 UTC
Players constantly keep getting timed out and re-connected but there is no dropout on audio or any issues what so ever.

![image](https://user-images.githubusercontent.com/33637910/110976434-8b7d9500-8369-11eb-8338-4091c6109e80.png)

Is there a way to just disable these messages because they don't seem to be effecting anything at all.

**Comment by henkelmax** [comment] 2021-03-12 17:35
Duplicate of #81

**Closed by henkelmax** 2021-03-12 17:35 UTC
Labels: invalid
