### ISSUE TITLE
Friend cannot hear me when we use a group chat

### ISSUE THREAD

**Issue by woutwoot** [henkelmax/simple-voice-chat#436] opened 2022-07-22 21:41 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
I'm having an issue with group chats... For some reason, with proximity chat everything works fine, but as soon as we create a group chat and my friend joins, he is no longer able to hear me while I can still hear him. I can also see my "head" lighting up but he can't. Connectivity tests are all fine.

**Steps to reproduce the issue**
Create (and have friend join) or join a group chat that he created.

**Expected behavior**
I expected my friend would be able to hear me when both of us are in the group chat.

**Log files**
Both client and server logs do not contain anything interesting. I understand this will probably be hard to reproduce...

**Versions**
- Minecraft version 1.18.2
- forge-1.18.2-40.1.60
- voicechat-forge-1.18.2-2.2.52.jar

**Other mods**
We are currently playing All The Mods 7 so we do have a bunch of mods installed. Testing without them is very difficult.

**Comment by woutwoot** [comment] 2022-07-22 21:51
While going through issues, it's actually very similar to this one: https://github.com/henkelmax/simple-voice-chat/issues/395
He crashes when he presses the mute button. I will ask him (and try to explain how) to provide logs.

**Comment by henkelmax** [comment] 2022-07-22 22:05
You are using an outdated forge version. Forge had a breaking change in 41.0.94

**Comment by woutwoot** [comment] 2022-07-23 08:00
@henkelmax Should that fix the issue, or is it unrelated? As in, is this known to be the cause?

**Comment by henkelmax** [comment] 2022-07-23 09:36
This is the cause

**Comment by woutwoot** [comment] 2022-07-23 09:44
@henkelmax I'm sorry to keep bugging you but as far as I can tell the latest Forge version for 1.18.2 is 40.1.68, that's still an older version than the version you mention. Does that mean the mod is effectively (partially) broken for 1.18.2 and the only fix is switching to 1.19?

**Comment by henkelmax** [comment] 2022-07-23 10:31
Ah sorry, I thought you were on 1.19

**Comment by henkelmax** [comment] 2022-07-23 10:32
> While going through issues, it's actually very similar to this one: https://github.com/henkelmax/simple-voice-chat/issues/395

So your game is crashing?

**Comment by woutwoot** [comment] 2022-07-23 10:37
Well, the main issue is him not being able to hear me in a group chat. That's really what's stopping us from using the mod fully. Secondly, when he clicks the mute button, his game crashes. I will try and get the stacktrace from him and get back to you.

**Comment by henkelmax** [comment] 2022-07-23 10:37
I need the full logs, not only the crash report.

**Comment by henkelmax** [comment] 2022-07-24 10:35
#395 is solved: https://github.com/henkelmax/simple-voice-chat/issues/395#issuecomment-1193289406

I'm gonna close this issue again. If you get the logs and that's not the issue you were having, let me know and I'll reopen it.

**Closed as completed by henkelmax** 2022-07-24 10:35 UTC
Labels: bug

**Comment by woutwoot** [comment] 2022-07-24 10:41
For us it does not have to do with replacing the jar.

I had my friend over yesterday and was planning to try again so I could get you the proper logs etc... Suddenly we did not have any issues and group chat worked. Because of that, I'm not sure what the actual cause was, but we will try again.

Difference between yesterday and before is that my friend was now in the same network the server is hosted on (like me). We will test again remotely later, will report if the issue persists then. (so it's ok this is closed for now)

**Comment by woutwoot** [comment] 2022-07-27 18:15
[crash-2022-07-26_21.14.18-client.txt](https://github.com/henkelmax/simple-voice-chat/files/9202504/crash-2022-07-26_21.14.18-client.txt)
This is the report I've gotten from him. This is when he clicked the mute button. Maybe it helps?

**Comment by henkelmax** [comment] 2022-07-27 18:16
Yep same issue as #395 
No clue why it happens for him, but it looks like something is modifying the jar while running the game.

**Comment by woutwoot** [comment] 2022-07-27 18:17
Maybe some virus scanner? We're using GDLauncher and are not doing anything special. Will ask what kind of software he has active on his PC.

**Comment by henkelmax** [comment] 2022-07-27 18:18
Tell him to try another launcher maybe. Your antivirus could also cause issues I guess...
