### ISSUE TITLE
Push to talk can be pressed while typing in-game

### ISSUE THREAD

**Issue by Watermalia** [henkelmax/simple-voice-chat#195] opened 2021-05-27 04:46 UTC
**Bug description**
While typing in the in-game voice chat or typing on a sign, voice chat will still occur through the push to talk key.

**Steps to reproduce the issue**
1. In game, open text chat or place a sign
2. Hold down Push to Talk key
3. Voice chat will activate

**Expected behavior**
Voice chat should not activate when using in-game text chat. This will make it so that your mic does not pop in or out if you use the push to talk key to type something in-game.

**Versions**
- Minecraft version = 1.16.5
- Forge version = 36.1.24
- Mod version = 1.3.9

**Comment by henkelmax** [comment] 2021-05-27 07:06
Duplicate of #137

**Closed by henkelmax** 2021-05-27 07:06 UTC
Labels: bug
