### ISSUE TITLE
A few problems with the mod

### ISSUE THREAD

**Issue by rickerd-ops** [henkelmax/simple-voice-chat#53] opened 2021-02-17 18:59 UTC
So i have been trying to fix the mod for myself for 3 days and cant get over it.

My problems: Pc hosted:

- People can hear him, but he cant hear the players (already another issue athats open.) This is not for every player. Out of 7 players for 4 players the mod works fine, for 3 players the mod is not working good.
- for some players the voice mod works for only 1 minute, after that the voice mod will not work anymore. V still works for them.

Server hosted:
- when i want the mod running on a host server. The voice sounds like a robot and will not detect good your voice. Is that a problem with the tcp/udp port? I have asked the provider about the ports that they have open to use.

The second issue, is that a frequent problem?

**Comment by henkelmax** [comment] 2021-02-17 20:15
Duplicate of #51, #46, #23
These are all known issues and a fix is on the way.

**Closed by henkelmax** 2021-02-17 20:15 UTC
