### ISSUE TITLE
"Client not connected"

### ISSUE THREAD

**Issue by K9Kr** [henkelmax/simple-voice-chat#124] opened 2021-03-25 18:20 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
"Client not connected" after /voicechat test

**Steps to reproduce the issue**
1. I went to my server
2. I saw plugin the lower left on my screen
3. I typed in chat "/voicechat test (my nick)
4. And it said: "Client not connected"

**Expected behavior**
I expected Simple Voice Chat mod to work 

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.16.5
- Forge version 1.16.5
- Mod version 1.16.5

**Other mods**
I also have installed OptiFine alongside with Simple Voice Chat mod

**Screenshots (Optional)**
Screenshots of the issue.
![proximity voice chat](https://user-images.githubusercontent.com/81383438/112523161-bff84480-8d9e-11eb-9cdf-1f903e2154ce.png)

**Comment by henkelmax** [comment] 2021-03-25 18:21
Duplicate of #112, #104, #98, #97, #115 and many others.

**Closed by henkelmax** 2021-03-25 18:21 UTC
Labels: bug

**Comment by JustClouded** [comment] 2022-11-16 16:11
> Duplicate of #112, #104, #98, #97, #115 and many others.
im also having problems with this and i dont get your reply. so help??
