### ISSUE TITLE
Timing out over WAN

### ISSUE THREAD

**Issue by 0undefined** [henkelmax/simple-voice-chat#106] opened 2021-03-14 12:36 UTC
**Bug description**
I am hosting this on my PC, connecting through `localhost` and `lan` works fine, but connecting through WAN doesn't work for me. I get "Voice chat unavailable" when connecting through WAN. I have followed the `netcat` steps and verified that the port is open is open and forwarded correctly, all went successfully. Bind address is `0.0.0.0` (default?) and I've changed the port to `25566`, which shouldn't be an issue given that I have checked the forwarding with netcat.

The server logs says that I successfully authenticate, followed by a timeout, a reconnect and a new secret is sent followed by another successful authentication. However, testing with `/voicechat test <username>` gives yet another timeout.
The server is running on Linux 5.11.5, x86_64.

This has also been replicated on a separate PC on the same network, however, after logging in through _another network_ it to worked, I believe it's caused by the port has already been bound for the server, or perhaps caused by an actual bug. I'd suggest if you write this in the FAQ, unless there's a solution for this with some better forwarding than what I've done. (but then again, why would I connect through WAN when I'm on the same LAN).
Closing this as won't fix is fine, but I think people should know about this quirk.

**Steps to reproduce the issue** (if reproducable at all, and not just something to do with my setup)
1. Start forge server with voice chat.
2. Login to the server from same network through WAN
3. type `/voicechat test <username>`

**Expected behavior**
That the voicechat authenticates once and successfully connects to client.

**Log files**
[log](https://gist.github.com/0undefined/7676b352074b9e42af5004bffd81c98d)

**Versions**
- Minecraft version: `1.16.5`
- Forge version: `36.0.55`
- Mod version: `1.16.5-1.0.16`

**Other mods**
No other server-side or client-side mods.

**Comment by 0undefined** [comment] 2021-03-14 12:38
What strikes me as odd is that it authenticates successfully and doesn't outright f-up the connection right away, but instead times out after the connection is established.

**Comment by henkelmax** [comment] 2021-03-14 12:38
Duplicate of #81

**Closed by henkelmax** 2021-03-14 12:38 UTC
Labels: bug
