### ISSUE TITLE
Still getting "Voice chat unavailable"

### ISSUE THREAD

**Issue by ArvickC** [henkelmax/simple-voice-chat#203] opened 2021-06-04 21:15 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
I run a Forge 1.16.3 server on Apex Hosting. I've gone through all the steps on the wiki, as well as asking Apex Hosting if they, themselves could open the port. They have also seen that the voicechat server is starting correctly and binding is set. I've done everything I think I can do, and I don't know what's happening. I still get the "Voice chat unavailable" error.

**Steps to reproduce the issue**
1. Install the mod [Forge 1.16.3](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/3107689)
2. Set up mod (binding, ports, etc.)
3. Join [Minecraft] server
4. Click your set GUI button, and get the error message on action bar.

**Expected behavior**
What should happen is, the GUI should open showing the group and settings buttons.

**Versions**
- Minecraft version 1.16.3
- Forge version 1.16.3 (doesn't say on Apex Hosting panel)
- Mod version 1.16.3-1.0.1

**Other mods**
~~Mods are attached to this message.~~

Edit: File wouldn't upload. Uploaded it to [Mediafire](https://www.mediafire.com/file/jn9tr3bxc2wj9az/AllMods.zip/file)

**Comment by henkelmax** [comment] 2021-06-04 21:23
I can't help you with that. You need to ask the support of your hoster.
Also 1.16.3 is not supported anymore, please consider updating to 1.16.5.

Duplicate of #112, #104, #98, #97, #115, #124, #146, #152, #153, #160, #169, #178 and many others.

**Closed by henkelmax** 2021-06-04 21:23 UTC
Labels: help wanted
