### ISSUE TITLE
How to fix the "Voice chat unavailable" problem

### ISSUE THREAD

**Issue by ShadeeRogue** [henkelmax/simple-voice-chat#152] opened 2021-04-13 03:17 UTC
I downloaded the mod to use in my friends server and whenever I press the button to turn on the mic it says "Voice chat unavailable". I looked up how to fix it and I couldn't find anything about it.
![2021-04-12_23 17 10](https://user-images.githubusercontent.com/82428559/114491824-4c02cc80-9be5-11eb-9497-941f97702301.png)

**Comment by henkelmax** [comment] 2021-04-13 06:31
Duplicate of #112, #104, #98, #97, #115, #124, #146 and many others.

**Closed by henkelmax** 2021-04-13 06:31 UTC
Labels: question
