### ISSUE TITLE
Client crashes when clicking on "groups" button

### ISSUE THREAD

**Issue by redstonerti** [henkelmax/simple-voice-chat#510] opened 2022-12-18 17:25 UTC
Using fabric 1.19.2
I was playing in a server with a friend and clicked the group button, and I just got kicked to the desktop. This doesn't happen every time I press that button. It was very random
https://mclo.gs/cDh1HoP

**Comment by henkelmax** [comment] 2022-12-18 17:26
Duplicate of #509
Can you post your information there?

Also next time, please fill out the bug template.

**Closed as not planned by henkelmax** 2022-12-18 17:26 UTC
Labels: duplicate
