### ISSUE TITLE
Mod Compatibility: Dynamic sound filter (fabric)

### ISSUE THREAD

**Issue by MokkaCicc** [henkelmax/simple-voice-chat#150] opened 2021-04-09 11:13 UTC
**Is your feature request related to a problem? Please describe.**
The dynamic sound filter mod adds sound effects (ex: reverb in caves) but it doesn't affect voice chat.

**Describe the solution you'd like**
The filters need to be applied to the voice chat.

**Describe alternatives you've considered**
None

**Additional context**
I use the fabric version and Dynamic sound filter is a fabric-only mod. If you also want to add this feature to forge, Sound Filters is a similar mod.

**Comment by henkelmax** [comment] 2021-04-09 11:15
Duplicate of #96 and #114

**Closed by henkelmax** 2021-04-09 11:15 UTC
Labels: enhancement
