### ISSUE TITLE
Cant hear anyone no one can hear me.

### ISSUE THREAD

**Issue by SnowyMadLad** [henkelmax/simple-voice-chat#51] opened 2021-02-14 00:01 UTC
**Bug description**
Basically once i launch my game go on my friends server ( everyone has the latest version of the mod) Go up to them start talking, I can only hear them for a split second once i join and then its just silence. its the same for them. And before you say anything, Yes i have checked all my inputs and even did a mic test! Everything worked i could hear myself and it was registering i even saw my little mic thing going up in the corner. My friend who owns the server did a voice packet test on me and it came back request timed out. Im not sure how this happened or how you can replicate it. 
I have tried disabling my firewall aswell! I also, never got a pop up, Apparently theres a pop up you need that says the servers which i never got.
*Logs* 
>....=>.... [03:15:58] [Server thread/INFO] [minecraft/DedicatedServer]: Sending packet...
>.... [03:15:58] [Server thread/INFO] [minecraft/DedicatedServer]: Packet sent. Waiting for response...
>.... [03:15:59] [VoiceChatPacketProcessingThread/INFO] [minecraft/DedicatedServer]: Request timed out
*Once owner requests packet*
. [03:09:04] [Server thread/INFO] [minecraft/PlayerList]: Tinley[/99.238.53.63:57694] logged in with entity id 28807 at (-703.2419027941424, 68.0, 1088.2904485103345)
>.... [03:09:04] [Server thread/INFO] [minecraft/DedicatedServer]: Tinley joined the game
>.... [03:09:04] [Server thread/INFO] [voicechat/]: Sent secret to Tinley
>.... [03:09:05] [Server thread/INFO] [minecraft/DedicatedServer]: [Mastereloadingg: Client not connected]
>.... [03:09:06] [Server thread/INFO] [minecraft/DedicatedServer]: [Mastereloadingg: Client not connected]
>.... [03:09:06] [Server thread/INFO] [minecraft/DedicatedServer]: [Mastereloadingg: Client not connected]
>.... [03:09:06] [VoiceChatPacketProcessingThread/INFO] [voicechat/]: Successfully authenticated player c7dc7826-2bd1-45af-ab03-dd033c665eb4
*once i join*

**Steps to reproduce the issue**
1. Launch minecraft
2. Go on a server
3. Talk

**Expected behavior**
Did not expect this to happen.

**Versions**
- Minecraft version 1.16.4
- Forge version 35.1.4
- Mod version Latest voice mod version

**Other mods**
No other mods. Just forge.

**Comment by SnowyMadLad** [comment] 2021-02-14 01:56
Also please direct me towards a fix.

**Comment by henkelmax** [comment] 2021-02-14 08:59
Please send me the complete logs of the clients and the server.
This might also be related to #23.
One other question: Are you using MacOS?

**Comment by asdfghjkl403622** [comment] 2021-02-14 18:06
Hello!

I am having a similar issue, here is my server log: https://pastebin.com/ZpCCcjgY

**Comment by SnowyMadLad** [comment] 2021-02-14 18:46
> Please send me the complete logs of the clients and the server.
> This might also be related to #23.
> One other question: Are you using MacOS?

Not using Mac im a windows user. No one can hear me nor can i hear them so could be related but possibly not. Ill try to get some complete logs for ya but you can use the guy above me's logs to find a fix.

**Comment by henkelmax** [comment] 2021-02-14 18:49
> I also, never got a pop up, Apparently theres a pop up you need that says the servers which i never got.

Which popup do you mean?

**Comment by SnowyMadLad** [comment] 2021-02-14 19:24
My friends said at the start they got a pop up inviting them to the servers with a java menu but i never got it. Did you add that?

**Comment by henkelmax** [comment] 2021-02-14 19:26
This is not a feature of the mod. Are you sure you are using the right mod?

**Comment by SnowyMadLad** [comment] 2021-02-14 20:33
Yup. This is it. Not sure they just said they got it.

**Comment by asdfghjkl403622** [comment] 2021-02-14 22:58
is your friend on MacOS? maybe it's something to do with inter-operating system compatibility?

**Comment by SnowyMadLad** [comment] 2021-02-14 23:06
No everyone is on windows.

**Comment by asdfghjkl403622** [comment] 2021-02-14 23:14
weird, I hope we can find a solution soon, I don't know what the issue is

**Comment by SnowyMadLad** [comment] 2021-02-14 23:22
Me neither. I wanted to play smp with my friends not deal with bugs.

**Comment by asdfghjkl403622** [comment] 2021-02-14 23:26
same man! I just recently got my server up, and most of the other mods didn't have issues. Although the issues with this one make sense, since it's a little special.

**Comment by henkelmax** [comment] 2021-02-15 08:19
I think I have figured out the problem. It has to do with some networks dropping UDP packets larger than a specific size. It might take a while until I fixed it.

**Comment by asdfghjkl403622** [comment] 2021-02-16 02:03
any progress? Because if this is actually a bug, then imma have to find another solution.

**Comment by henkelmax** [comment] 2021-02-16 07:31
Working on it.

**Comment by henkelmax** [comment] 2021-02-16 09:43
It should be fixed with the latest version. Please let me know if it works. You might have to change a config value if it doesn't work.

**Comment by gurhoter** [comment] 2021-02-16 17:45
i have the same excact problem. my friends started an smp with this vc mod and another terrain mod, everyone can talk with each other with not so much lag (we are about 12 people on the server), but i am the only person who's voice chat doesn't work, tried reinstalling with the latest version, it worked for a minute but then after a restart it stopped working. tried reinstalling again, and now i hear just scraps of sounds when people talk, same goes for the opposite side.
also checked the logs, says my "authentication was succesful".    
i saw henkelmax wrote to change a config value if it doesn't work, how do i do that?
any way i can fix it ?

**Comment by SnowyMadLad** [comment] 2021-02-16 17:56
Im gonna try it out lets see if it works!

**Comment by henkelmax** [comment] 2021-02-16 19:52
> i have the same excact problem. my friends started an smp with this vc mod and another terrain mod, everyone can talk with each other with not so much lag (we are about 12 people on the server), but i am the only person who's voice chat doesn't work, tried reinstalling with the latest version, it worked for a minute but then after a restart it stopped working. tried reinstalling again, and now i hear just scraps of sounds when people talk, same goes for the opposite side.
> also checked the logs, says my "authentication was succesful".
> i saw henkelmax wrote to change a config value if it doesn't work, how do i do that?
> any way i can fix it ?

If your voice doesn't arrive on the server you might have a problem with the MTU size of your network.
Try running the command `ping modrepo.de -f -l 1000`. If it says `Packet needs to be fragmented`, you need to decrease the `mtu_size` config option to a lower value.

Also make sure the server has the exact same voicechat mod version that you have, since the packet size changed with the last update.

**Closed** 2021-02-19 09:32 UTC
Labels: bug
