### ISSUE TITLE
[Loop] Trying to authenticate voice connection ( Client side log Spam )

### ISSUE THREAD

**Issue by xR4YM0ND** [henkelmax/simple-voice-chat#456] opened 2022-08-25 14:48 UTC
### Server side:
I added a second port on our server cause of Raknetify which needs the same port as server for connection

So i opened the port and edit the config file to this port

### Problem
The client log gets spamed and it seems that there is no connection between client and server

[client latest.log](https://gist.github.com/SpigotDE/dc753eff4e3ec9db30b06eb1d39402f1)
[server latest.log](https://gist.github.com/SpigotDE/f1f8e72cf7200e0c73b9aff64e8ec068)

Do you have any ideas why its not working?

**Comment by henkelmax** [comment] 2022-08-25 15:00
Duplicate of #449

If you need help setting up the mod visit the discord.

**Closed as not planned by henkelmax** 2022-08-25 15:00 UTC
Labels: help wanted
