### ISSUE TITLE
VC Mod sometimes becomes unavailable

### ISSUE THREAD

**Issue by CrypiYT** [henkelmax/simple-voice-chat#209] opened 2021-06-07 21:19 UTC
**Bug description**
Playing on a server with a few people (around 15-20) and then suddenly the voice chat becomes unavailable

**Steps to reproduce the issue**
1. Play with a few players
2. Everyone needs to talk
3. Error occourse

**Expected behavior**
I expected it to work just as usual with no interruptions at all

(Log files are currently unavailable but I'll add them here asap)

**Comment by henkelmax** [comment] 2021-06-08 07:21
Please fill out the complete bug template.
What are the specs of your server (CPU cores, clock speed, RAM)?

**Comment by CrypiYT** [comment] 2021-06-08 15:14
CPU: Ryzen 7 3800x 3.9 GHz 8c/16t NVME RAID1 DDR4 2666 MT/s
RAM: 6 GB

Minecraft Version: 1.16.5
Fabric Version: 0.11.3
Mod Version: 1.3.10+

**Comment by henkelmax** [comment] 2021-06-08 15:16
I also need your logs.
Can you tell me the CPU core usages, when this happens?

**Comment by CrypiYT** [comment] 2021-06-08 15:17
The highest amount of the CPU that was used was around 50% and RAM around 70% at highest peaks, as I don't own the server my self and just operate it I need to wait for the Owner to get online and send me the log files D:

**Comment by henkelmax** [comment] 2021-06-08 15:21
It is important to look at the individual core usages, since one core could be completely utilized while others aren't used at all.

Make sure to send me the logs of the client and server of this incident.

Please also make sure to test the `/voicechat test` command when the disconnection occurs. (Please include this in the client and server logs)

**Comment by CrypiYT** [comment] 2021-06-08 15:50
I wrote all of the clients I need the logs from them now, I'll also execute the command asap but not everyone is ready to play rn to reproduce the error. I hope that I'll have most of the Logs from all clients + the Server after today :/. Also the Serverhoster we are using doesn't allow us to see the individual usage of the CPU cores so we are just stuck with that one value of 50%

**Comment by henkelmax** [comment] 2021-06-08 15:53
I only need the logs of one client that disconnects. It isn't necessary to get the logs of everyone.

**Comment by henkelmax** [comment] 2021-06-09 12:22
I pushed a new update. Can you please send me the logs of this happening in this version:

https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/3344919

**Comment by CrypiYT** [comment] 2021-06-09 15:20
Yeah of course I can do it, thank you. But we have to wait until Sunday as this is the next time all of us will be playing :/.
I'll send the logs asap

**Comment by henkelmax** [comment] 2021-06-09 15:21
Thank you!
This update unfortunately won't fix the actual issue, but I added log outputs, that will hopefully narrow down the source of the problem.

**Comment by CrypiYT** [comment] 2021-06-13 20:19
So we finished or session, but we didn't run into any "voice mod crashes" but player had an insanely high ping.
When the mod was struggling I used the /voicechat test command and it tell me I everyone had a ping around 2000ms.
I also got the server logs (finally :p)
I hope you can help me with this issue :D

[2021-06-13-5.log](https://github.com/henkelmax/simple-voice-chat/files/6644564/2021-06-13-5.log)
[2021-06-13-6.log](https://github.com/henkelmax/simple-voice-chat/files/6644565/2021-06-13-6.log)

**Comment by henkelmax** [comment] 2021-06-13 20:44
> [17:04:32] [VoiceChatPacketProcessingThread/WARN]: Dropping voice chat packets! Your Server might be overloaded!
[17:04:32] [VoiceChatPacketProcessingThread/WARN]: Packet queue has 400 packets

The problem is definitely the processing power of your server.
It can't handle decrypting and processing all voice chat packets.

I might add a few optimizations on the future, but don't expect it to improve that much...

**Closed as completed by henkelmax** 2021-06-13 20:44 UTC
Labels: bug
