### ISSUE TITLE
Cannot hear anyone else

### ISSUE THREAD

**Issue by asdfghjkl403622** [henkelmax/simple-voice-chat#52] opened 2021-02-14 17:38 UTC
I am trying to use this mod on my 1.16.5 server, and I am on MacOS and my friend is on windows. I used `/voicechat test` on me and my friend and it says that we have a connection, with the amount of time it takes to get the ping back (I hat my friend install NetCat). and we can't hear each other. 

[Server Log](https://pastebin.com/ZpCCcjgY)

And I should add, we can see the speaker icon next to each other's usernames when we speak, and when we use microphone test we can hear ourselves. so either it's a issue with the speaker or something else.

**Comment by henkelmax** [comment] 2021-02-14 17:43
Duplicate of #51 #24 and #23
Please add your logs to one of the other issues.

**Closed by henkelmax** 2021-02-14 17:43 UTC
